### ISSUE TITLE
能不能加入坚果云同步用户词汇的功能

### ISSUE THREAD

**Issue by Tenadults** [brglng/rime-xhup#12]
小鹤原生的输入法没有云同步的功能，可不可以加入一个使用坚果云云同步的功能，这样不会增加额外的服务器的费用也可以进行云同步，这样用户词库同步就可以更加方便一点。

**Comment by brglng** [comment]
你可以使用 rime 的同步功能，把 rime 的配置放在坚果云里面。不过这个跟本项目没什么关系，本项目只是个自定义输入法配置而已。
