### ISSUE TITLE
关于字典(xhup.dict.yaml xhup_luna.dict.yaml)中没有的一些字

### ISSUE THREAD

**Issue by xixian2106** [brglng/rime-xhup#2]
例如"愀qiǎo"(出自 《赤壁赋》),字典中没有所以没办法输入,用小鹤官方的输入法可以,希望可以更新一下.

平时恰好遇见了缺失的可以手动补全一下,不过缺失的实在是不少,如果能从小鹤官方字典中转换过来的话就会好很多 XD

**Comment by JackChen007** [comment]
同问，如何 从 官方 转换 并 得到 码表

**Comment by xixian2106** [comment]
@JackChen007 我觉得你可以把 [Unicode字符集](https://www.qqxiuzi.cn/zh/hanzi-unicode-bianma.php) 里面的汉字都在 [小鹤编码查询](http://www.xhup.club/) 这里查一遍,然后提取得到的结果自己整理一个码表出来

**Comment by brglng** [comment]
目前小鹤双拼官方已锁定码表，不再免费提供下载。我已使用小鹤双拼官方提供的「百度输入法挂接码表」中提供的码表更新了此版码表。如果有更好的方法望告知，谢谢。

**Comment by brglng** [comment]
> @JackChen007 我觉得你可以把 [Unicode字符集](https://www.qqxiuzi.cn/zh/hanzi-unicode-bianma.php) 里面的汉字都在 [小鹤编码查询](http://www.xhup.club/) 这里查一遍,然后提取得到的结果自己整理一个码表出来.
> 
> 目前只会这个笨方法...我可以为你提供一份我得到的结果的文件,可以看一下这个项目里 [我的fork](https://github.com/xixian2106/rime-xhup-dict/tree/rime-xhup-dict),之后就要按照你自己的需求来进行编辑了,我目前正在按照我自己的需求做. _(:з」∠)_

用这种方法的问题是，没有词的码表。

**Comment by BobCromwell** [comment]
> 目前小鹤双拼官方已锁定码表，不再免费提供下载。我已使用小鹤双拼官方提供的「百度输入法挂接码表」中提供的码表更新了此版码表。如果有更好的方法望告知，谢谢。

不是很理解官方为什么要锁定码表...

**Comment by alswl** [comment]
> 用这种方法的问题是，没有词的码表。

词的码表根据字的码表生成一份就可以了，算法不是固定的么？

**Comment by alswl** [comment]
> @JackChen007 我觉得你可以把 [Unicode字符集](https://www.qqxiuzi.cn/zh/hanzi-unicode-bianma.php) 里面的汉字都在 [小鹤编码查询](http://www.xhup.club/) 这里查一遍,然后提取得到的结果自己整理一个码表出来.

还有一种办法，用现在的 precompile bin 逆向一下，计算次数也不多 26^4。
