### ISSUE TITLE
更新到最新的码表

### ISSUE THREAD

**Issue by brglng** [brglng/rime-xhup#3]
更新到小鹤双拼最新码表。
#2

**Comment by brglng** [comment]
最近版本反查改成了 oi，README 忘记更新了，谢谢提醒。
至于 ' ; 分词，空格上屏等无效，我测试没有问题。如果你用的是鼠须管的话，很可能是因为鼠须管使用的 librime 版本太低导致的。可以尝试一下 XIME。
「录」的码确实不正确。码表是从「百度输入法挂接」导入的，那个码表有问题，我修改一下。感谢指出。
另外，与此 issue 无关的问题请开新 issue 来提，谢谢。

**Comment by brglng** [comment]
目前并没有好的方法来获取最新的完整码，这确实是一个问题。

**Comment by brglng** [comment]
前面的问题已经修复。

**Comment by Bravo911** [comment]
完整的码表是否能从小鹤网盘中的,鹤音形irime版forIOS里提取或者沿用呢,其他问题,我去新开issue

**Comment by brglng** [comment]
iRime 里只有编译好的码表

**Comment by Bravo911** [comment]
近日,我咨询了鹤大,他给了一个方法.
1.鼠须管可以像小鹤同文版一样,直接用封闭码表bin文件.就是需要保证rime版本和bin文件一致.
2.目前最新的小鹤音形,用的是rime-1.2.9-238-g2387dfb-arm64-v8a
3.我自己理解的,rime版本应该是和librime（1.2.9+）是同一个东西,我猜测的,不确定
4.如果能将把Squirrel.app 换成 1.2.9版本,就应该能直接用官方的码表bin文件
5.第4点成立的话,那么不需要用dict文本字典文件部署生成bin码表了,直接就用官方的bin
6.如https://www.jianshu.com/p/5a16b85b9035文章所写的一样,鹤大并没有去更新librime为1.3.0
总结,自己弄个和官方bin匹配的Squirrel.app(1.2.9),然后直接就把官方的bin文件复制到~rime\build文件夹中替换之前的；或者等鹤大更新到rime-1.3.0
ps以上对于你来说都不是问题吧,期待你的更新.

**Comment by Bravo911** [comment]
对你来说,除了时间,其他应该都不是问题.

**Comment by Bravo911** [comment]
大哥,20多天过去了,有什么进展了吗？

**Comment by lan542662** [comment]
> 等我有空试试直接使用 iRime 或小鹤双拼同文版中的 bin 码表，如果可以成功的话，我将删除 dict 文件，然后使用官方的 bin 码表来替代。

有几个小问题，
1 比较麻烦。涉及到太多的bulid里的bin文件，还有外面的配置和txt文件(用户自定义码表)，太多了。显得杂乱。
2 这样同步rime会出现错误，因为没有原始的dict文件。

**Comment by brglng** [comment]
https://github.com/brglng/rime-xhup/commit/78cf7591f65d94a85c6885d82a43bf5d7a107a47 已从官方提取二进制码表，并更新方案配置
