### ISSUE TITLE
分词，空格上屏,无法使用的问题

### ISSUE THREAD

**Issue by Bravo911** [brglng/rime-xhup#4]
先说重点,还是想问,能否提供你mac上目前使用鼠须管的~/Library/Rime文件的方案配置备份.@捂脸
1.出现问题的情况环境:
我用的是链接: https://pan.baidu.com/s/1Bm2MFhjB3Qgrp2xYKj2TJg 密码: bkw5这里的方案配置, 
librime的版本是写的1.30,除了分词，空格上屏,无法使用的问题,其他使用完美,配色等都合胃口.
2.我将rime-xhup的更新,复制到上面的1.30的rime文件中使用的.
3.确实喜欢你的整体配置,就跑到这里来问了.
4.以我的水平暂时没其他的解决方法了.做工程的人,能跑到github上提issues也够拼了.
再次强调重点,并感谢你的回复!

**Comment by Bravo911** [comment]
终于被我研究出来了，原来是我没有在，default.custom.yaml中将两这两个方案开启。
我都被我自己蠢哭了！
就是还有个问题，在连打的情况下，如何次选啊？可以告诉下吗？

**Comment by brglng** [comment]
请问你说的「连打情况下的次选」，具体是什么样的需求，能否详细描述一下？

**Comment by Bravo911** [comment]
`    - {accept: bracketleft, send: Page_Up, when: has_menu} # [上翻页
    - {accept: bracketright, send: Page_Down, when: has_menu} # ]下翻页
    - {accept: ";", send: 2, when: composing}--这个被连打的分词占用了,所以我就不会次选了.😂
    - {accept: comma, send: 2, when: composing}`
1是这样的,我自己习惯了用;分号进行次选,但是连打是用;分号做连打的分词,这样的情况下,我就不能进行次选了,
2这个主要的原因其实也是在我的,因为我并不是会所有字词的全码,所以才会出现,连打要进行次选的情况的.
3.目前这个不是主要问题,我自己想通了之后就没在纠结他了,反而现在特别想用上小鹤双拼官方一致的码表.
期待你的进展✌️
