### ISSUE TITLE
部署错误，日志文件提示缺少flypydz.schema.yaml

### ISSUE THREAD

**Issue by bosconb** [brglng/rime-xhup#7]
环境：macOS Mojave 10.14.3 (18D42)
版本：Squirrel 0.11.0

> E0610 11:17:40.897439 223690752 config_data.cc:71] Error parsing YAML: yaml-cpp: error at line 67, column 6: end of map not found
> E0610 11:17:43.320396 223690752 deployment_tasks.cc:319] Error updating schema: nonexistent file '/Users/dazkarieh/Library/Rime/flypydz.schema.yaml'.
> 
试过把bin文件放在build目录下，仍然报错。搜了一下，不光我存在这个问题
[How to use precompiled dictionary files](https://github.com/rime/ibus-rime/issues/70)，请问该如何解决这个问题？

**Comment by brglng** [comment]
无法解决，只有拿到小鹤双拼官方的 dict 文件才能彻底解决。

**Comment by brglng** [comment]
已更新，使用小鹤双拼官方 bin 文件可以解决。
